<?php
// Plugin definition
$plugin = array(
  'title' => t('Sanderson'),
  'icon' => 'bootstrap-sanderson.png',
  'category' => t('Bootstrap'),
  'theme' => 'bootstrap_sanderson',
  'regions' => array(
    'column1' => t('Row 1: First Column'),
    'column2' => t('Row 1: Second Column'),
    'secondarycolumn1' => t('Row 2: First Column'),
    'secondarycolumn2' => t('Row 2: Second Column'),
    'secondarycolumn3' => t('Row 2: Third Column'),
  ),
);
