<?php
// Plugin definition
$plugin = array(
  'title' => t('Webb Flipped'),
  'icon' => 'bootstrap-webb-flipped.png',
  'category' => t('Bootstrap'),
  'theme' => 'bootstrap_webb_flipped',
  'regions' => array(
    'header' => t('Header'),
    'sidebar' => t('Sidebar'),
    'contentheader' => t('Content Header'),
    'contentcolumn1' => t('Content Column 1'),
    'contentcolumn2' => t('Content Column 2'),
  ),
);
