<?php
// Plugin definition
$plugin = array(
  'title' => t('Sutro Double'),
  'icon' => 'bootstrap-sutro-double.png',
  'category' => t('Bootstrap'),
  'theme' => 'bootstrap_sutro_double',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'middle' => t('Middle'),
    'secondcolumn1' => t('Bottom First Column'),
    'secondcolumn2' => t('Bottom Second Column'),
    'footer' => t('Footer'),
  ),
);
